# Generated by Django 3.0.6 on 2020-05-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('card_number', models.CharField(max_length=32)),
                ('card_valid', models.CharField(max_length=16)),
                ('card_name', models.CharField(max_length=128)),
                ('card_cvv', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('class_id', models.IntegerField(default=0)),
                ('thing_id', models.IntegerField(default=0)),
                ('net_weight', models.IntegerField(default=0)),
                ('autobuy_enable', models.BooleanField(default=True)),
                ('autobuy_url', models.CharField(max_length=500)),
                ('device_mac', models.CharField(max_length=100)),
                ('power', models.IntegerField(default=80)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=100)),
                ('login_name', models.CharField(max_length=100)),
                ('login_password', models.CharField(max_length=200)),
            ],
        ),
    ]
