# Generated by Django 3.0.6 on 2020-05-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='owned_by',
            field=models.IntegerField(default=0),
        ),
    ]
