# Generated by Django 3.0.6 on 2020-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkall', '0002_thing_owned_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentMethod',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='class_id',
            new_name='clear_time',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='owned_by',
            new_name='watch_dog',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='thing_id',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='autobuy_enable',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='autobuy_url',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='device_mac',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='power',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='status',
        ),
        migrations.AddField(
            model_name='thing',
            name='phone',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(default='unnamed', max_length=100),
        ),
    ]
